### ISSUE TITLE
skip version check when a pr closes

### ISSUE THREAD

**Issue by manuel-lopez-lyb** [jmlopez-rod/m#43]
when using

```
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize, closed]
```

We may need to be able to run or rerun the job. Only skip the version check if the pr is closed.
